
version: "3.9"

services:
  db:
    container_name: wp_db
    hostname: wp_db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - net
## update WORDPRESS_TABLE_PREFIX_options set option_value='https://URL' where option_id<=2; #siteurl / home       

  wordpress:
    container_name: wp
    hostname: wp
    depends_on:
      - db
    #image: wordpress:php8.0
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  INSTALL_PLUGINS: 
    ports:
      - "127.0.0.1:9001:80"
    restart: always
    environment:
      WORDPRESS_DEBUG: 0
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: PREFIX_
 	    WORDPRESS_CONFIG_EXTRA: |
		    // Disallow file edit
		    define( 'DISALLOW_FILE_EDIT', true );     
      
    networks:
      - net
volumes:
  db_data: {}


networks:
  net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.1.24/29 #192.168.1.25 - 192.168.1.30 
    driver_opts:
      com.docker.network.bridge.name: wordpress_net
