name: build

on:
  push:
    branches:
    - dev
    - master
  pull_request:
    branches:
    - dev
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: cp ci.env.json env.json && ./wp-cli.sh --init --force
